name: Continuous Integration

<<<<<<< HEAD
=======

>>>>>>> b552960f43f79b4d762793a20cac789193573c71
on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Instalar pylint
        run: pip install pylint

      - name: Rodar pylint (sem falhar)
<<<<<<< HEAD
        run: pylint *.py || true
=======
        run: pylint *.py || true
    steps :
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Python Lint Code Scanning Action
        uses: advanced-security/python-lint-code-scanning-action@v1.1.1
        with:
        linter: pylint
>>>>>>> b552960f43f79b4d762793a20cac789193573c71
