name: Continuous Delivery

on:
  pull_request:
    branches:
      - main

jobs:
  deliver:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Simulando Continuous Delivery
        run: echo "Deploy realizado com sucesso"